alias agrep="alias | grep"
alias and="&&"
alias back="cd -"
alias chrome="open -a \"Google Chrome\""
alias de="drone exec --exclude git --exclude submodules"
alias dee="de --exclude"
alias dei="de --include"
alias drone="env -i /usr/local/bin/drone"
alias gcaf="gca --fixup"
alias gitn="git --no-pager"
alias personal="vim ~/personal_env"
alias py="/usr/local/opt/python@3.8/bin/python3"
alias show="declare -f"
alias vim="mvim -v"
alias git="hub"
alias pr="g pull-request --no-edit"
alias ci="g ci-status"
alias show-pr="g pr show"
alias python="py"

eval $(thefuck --alias)
